# Generated by Django 4.2.7 on 2023-11-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_menu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
